config-version: 0

debug: false
language: en

command-aliases:
  craft: [ "craft" ]

recipes:
  - id: amber
    permission: "craft.amber"
    result: "oraxen:amber/8"
    ingredients:
      - ""
      - "minecraft:diamond/32"
      - ""
      - "minecraft:diamond/32"
      - "minecraft:diamond/32"
      - "minecraft:diamond/32"
      - ""
      - "minecraft:diamond/32"
      - ""