config-version: 0

debug: false
language: en

# Always keep at least one alias for every command
command-aliases:
  craft: [ "craft" ]
  recipes: [ "recipes" ]

# Should vanilla recipes be craftable in the custom crafting table?
include-vanilla-recipes: false

# Should "vanilla" recipes registered by other plugins be craftable in the custom crafting table?
include-other-plugin-recipes: false

# Should the custom crafting table open instead of the vanilla crafting table
# when the player right clicks on a crafting table?
# Enabling this needs a server restart to take effect.
open-instead-of-crafting-table: false

# Should the custom crafting table open instead of the vanilla crafting table
# when the player shift right clicks a crafting table?
# Enabling this needs a server restart to take effect.
open-shift-click-crafting-table: false