config-version: 4

debug: false
language: en

# Always keep at least one alias for every command
command-aliases:
  craft: [ "craft" ]
  recipes: [ "recipes" ]
  merchants: [ "merchants" ]

# Should vanilla recipes be craftable in the custom crafting table?
# List the workbenches you want to include vanilla recipes in
include-vanilla-recipes: []

# Should "vanilla" recipes registered by other plugins be craftable in the custom crafting table?
# List the workbenches you want to include vanilla recipes in
include-other-plugin-recipes: []

# Should the custom crafting table open instead of the vanilla crafting table
# when the player right clicks on a crafting table?
# Enabling this needs a server restart to take effect.
# This uses the "default" workbench
open-instead-of-crafting-table: false

# Should the custom crafting table open instead of the vanilla crafting table
# when the player shift right clicks a crafting table?
# Enabling this needs a server restart to take effect.
# This uses the "default" workbench
open-shift-click-crafting-table: false

# This will be opened if the above options are enabled
default-workbench: "default"

# Should players auto discover vanilla recipes?
auto-discover-vanilla-recipes: false

# You can turn off the listeners completely to improve performance
# if you don't have any recipes that are using these.
# Changing these, requires a server restart to take effect.
craft-handlers:
  crafting-table: true
  smithing-table: true
  cauldron: true

# Only change these if you know what you're doing
# These values are in milliseconds and they are only applying for the workbench gui
click-cooldown: 75
shift-click-cooldown: 200

# Enabled hooks
hooks:
  AuroraQuests: true
  Quests: true
  BetonQuest: true
  Jobs: true
  ItemsAdder: true
  MythicMobs: true
  HeadDatabase: true
  AdvancedEnchantments: true