name: AuroraCrafting
version: '${version}'
main: gg.auroramc.crafting.AuroraCrafting
api-version: 1.20
authors: [ "erik_sz" ]
folia-supported: true
depend:
  - Aurora
softdepend:
  - AuroraQuests
  - Quests
  - BetonQuest
  - Jobs
  - MythicMobs
  - MythicCrucible
  - ItemsAdder
  - HeadDatabase
  - AdvancedEnchantments

permissions:
  aurora.crafting.*:
    children:
      aurora.crafting.use:
        default: true
      aurora.crafting.use.default:
        default: true
      aurora.crafting.use.interact:
        default: true
      aurora.crafting.recipes:
        default: true
      aurora.crafting.merchants:
        default: true
      aurora.crafting.admin.*:
        default: op
        children:
          - aurora.crafting.admin.reload
          - aurora.crafting.merchants.admin.open
          - aurora.crafting.admin.open